# Generated by Django 5.2.17 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ASSET_VALUATION', 'Asset Valuation & Depreciation'), ('MAINTENANCE_PERFORMANCE', 'Maintenance Performance & SLA'), ('SPARE_PARTS', 'Spare Parts Consumption & Cost'), ('COST_SUMMARY', 'Cost Summary (Accrual & Cost Center)')], max_length=64)),
                ('file_format', models.CharField(choices=[('XLSX', 'Excel Spreadsheet (.xlsx)'), ('PDF', 'PDF Document (.pdf)'), ('CSV', 'Comma Separated Values (.csv)')], default='XLSX', max_length=16)),
                ('filter_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=16)),
                ('progress_percent', models.IntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('minio_object_key', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_jobs',
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='export_jobs_tenant__d68afe_idx'), models.Index(fields=['tenant', 'user', 'status'], name='export_jobs_tenant__b8b64c_idx')],
            },
        ),
    ]
