# Generated by Django 5.2.17 on 2026-10-02 09:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_action_type'),
        ('users', '0002_alter_user_username_alter_role_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('skill_level', models.SmallIntegerField(default=1)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('coords_x', models.FloatField(default=0.0)),
                ('coords_y', models.FloatField(default=0.0)),
                ('floor_level', models.SmallIntegerField(default=1)),
                ('zone_id', models.CharField(blank=True, default='', max_length=64)),
                ('shift_end_time', models.DateTimeField(blank=True, null=True)),
                ('monthly_accumulated_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_on_duty', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technician_profiles',
                'indexes': [models.Index(fields=['tenant', 'availability_status', 'is_on_duty'], name='technician__tenant__8064bc_idx'), models.Index(fields=['tenant', 'user'], name='technician__tenant__854495_idx')],
            },
        ),
    ]
