# Generated by Django 5.2.17 on 2026-10-03 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_action_type'),
        ('users', '0003_technicianprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(blank=True, default='', max_length=255)),
                ('validity_months', models.IntegerField(default=12, help_text='Thời hạn hiệu lực theo tháng (0 = vô thời hạn)')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'certification_types',
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False, help_text='Ca trực kéo dài qua ngày hôm sau (ví dụ 22:00 - 06:00)')),
                ('color_code', models.CharField(default='#3b82f6', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'shift_templates',
            },
        ),
        migrations.CreateModel(
            name='TechnicianSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('ON_DUTY', 'On Duty / Đi ca'), ('OFF', 'Off / Nghỉ ca'), ('LEAVE', 'On Leave / Nghỉ phép')], default='ON_DUTY', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='users.shifttemplate')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'technician_schedules',
            },
        ),
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(blank=True, default='', max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Còn hiệu lực'), ('EXPIRED', 'Expired / Hết hạn'), ('REVOKED', 'Revoked / Bị thu hồi')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_certifications', to='users.certificationtype')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_certifications',
            },
        ),
        migrations.CreateModel(
            name='WorkforceSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='GENERAL', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'workforce_skills',
            },
        ),
        migrations.AddIndex(
            model_name='certificationtype',
            index=models.Index(fields=['tenant', 'code'], name='certificati_tenant__5570fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificationtype',
            unique_together={('code', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['tenant', 'code'], name='shift_templ_tenant__0b0075_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shifttemplate',
            unique_together={('code', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='technicianschedule',
            index=models.Index(fields=['tenant', 'work_date', 'status'], name='technician__tenant__ec68f6_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianschedule',
            index=models.Index(fields=['tenant', 'user', 'work_date'], name='technician__tenant__debd9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianschedule',
            unique_together={('tenant', 'user', 'work_date')},
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['tenant', 'user', 'status'], name='user_certif_tenant__3179a4_idx'),
        ),
        migrations.AddIndex(
            model_name='usercertification',
            index=models.Index(fields=['tenant', 'expiry_date'], name='user_certif_tenant__d73937_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceskill',
            index=models.Index(fields=['tenant', 'code'], name='workforce_s_tenant__a54484_idx'),
        ),
        migrations.AddIndex(
            model_name='workforceskill',
            index=models.Index(fields=['tenant', 'category', 'is_active'], name='workforce_s_tenant__d32dbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workforceskill',
            unique_together={('code', 'tenant')},
        ),
    ]
