# Generated by Django 5.2.17 on 2026-10-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_certificationtype_shifttemplate_technicianschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianschedule',
            name='duty_zone_id',
            field=models.CharField(blank=True, default='', help_text='Khu vực hoặc phân xưởng trực trong ca hôm nay', max_length=64),
        ),
    ]
