# Generated by Django 5.2.17 on 2026-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_technicianschedule_duty_zone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='max_shift_minutes',
            field=models.IntegerField(default=480, help_text='Thời gian làm việc tối đa trong ca (phút)'),
        ),
    ]
