# Generated by Django 6.1 on 2026-10-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_location_zone_type'),
        ('users', '0006_technicianprofile_max_shift_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='floorplan',
            field=models.ForeignKey(blank=True, help_text='Mặt bằng làm việc chính được gán cho nhân viên', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profiles', to='assets.location'),
        ),
    ]
