# Generated by Django 6.1 on 2026-08-28 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('tenant_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('service_plan', models.CharField(default='FREE', max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
    ]
