# Generated by Django 5.2.17 on 2026-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummytenantmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
