# Generated by Django 5.2.17 on 2026-09-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dummytenantmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(max_length=50),
        ),
    ]
