# Generated by Django 5.2.17 on 2026-08-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_meterreading'),
        ('core', '0004_alter_dummytenantmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hierarchytemplate',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hierarchytemplate',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='qr_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('qr_code', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('name', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='hierarchytemplate',
            unique_together={('name', 'tenant')},
        ),
    ]
