# Generated by Django 5.2.17 on 2026-09-20 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_created_by_alter_asset_updated_by_and_more'),
        ('core', '0004_alter_dummytenantmodel_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_trackable',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('OPERATING', 'Operating'), ('DOWN', 'Down'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired'), ('SCRAPPED', 'Scrapped'), ('DISPOSED', 'Disposed'), ('DECOMMISSIONED', 'Decommissioned'), ('DRAFT', 'Draft'), ('LOST', 'Lost'), ('SOLD', 'Sold')], default='OPERATIONAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'is_trackable', 'status'], name='assets_tenant__363e42_idx'),
        ),
    ]
