# Generated by Django 5.2.17 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_is_trackable_alter_asset_status_and_more'),
        ('core', '0005_alter_auditlog_action_type'),
        ('workorders', '0006_workorder_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='capitalized_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='asset',
            name='capitalized_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='asset',
            name='useful_life_years',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('ISSUE', 'Issue / Xuất kho'), ('RECEIPT', 'Receipt / Nhập kho GRN'), ('RETURN', 'Return / Hoàn trả'), ('ADJUSTMENT', 'Adjustment / Điều chỉnh')], default='ISSUE', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('cost_center_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateTimeField()),
                ('is_variance_adjustment', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='assets.sparepart')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='workorders.workorder')),
            ],
            options={
                'db_table': 'stock_transactions',
                'indexes': [models.Index(fields=['tenant', 'transaction_type', 'issue_date'], name='stock_trans_tenant__117709_idx'), models.Index(fields=['tenant', 'work_order'], name='stock_trans_tenant__34f250_idx')],
            },
        ),
    ]
