# Generated by Django 5.2.17 on 2026-10-02 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_capitalized_cost_asset_capitalized_date_and_more'),
        ('core', '0005_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='coords_x',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='coords_y',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='floor_level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='zone_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('available_quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'tools',
                'indexes': [models.Index(fields=['tenant', 'code'], name='tools_tenant__14f15b_idx')],
                'unique_together': {('code', 'tenant')},
            },
        ),
    ]
