# Generated by Django 5.2.17 on 2026-10-03 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_coords_x_asset_coords_y_asset_floor_level_and_more'),
        ('core', '0005_alter_auditlog_action_type'),
        ('workorders', '0008_workorder_coords_x_workorder_coords_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100)),
                ('asset_tag', models.CharField(blank=True, default='', max_length=100)),
                ('calibration_date', models.DateField(blank=True, help_text='Ngày kiểm định/hiệu chuẩn gần nhất', null=True)),
                ('calibration_due_date', models.DateField(blank=True, help_text='Ngày đến hạn hiệu chuẩn tiếp theo', null=True)),
                ('inspection_status', models.CharField(choices=[('PASSED', 'Đạt chuẩn'), ('DUE_SOON', 'Sắp đến hạn'), ('EXPIRED', 'Quá hạn kiểm định')], default='PASSED', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Khả dụng'), ('IN_USE', 'Đang sử dụng'), ('MAINTENANCE', 'Đang bảo dưỡng')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='assets.tool')),
            ],
            options={
                'db_table': 'tool_instances',
            },
        ),
        migrations.CreateModel(
            name='ToolReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved / Đã giữ chỗ'), ('IN_USE', 'In Use / Đang xuất dùng'), ('RETURNED', 'Returned / Đã hoàn trả'), ('CANCELLED', 'Cancelled / Đã hủy')], default='RESERVED', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='assets.tool')),
                ('tool_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='assets.toolinstance')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_reservations', to='workorders.workorder')),
            ],
            options={
                'db_table': 'tool_reservations',
            },
        ),
        migrations.AddIndex(
            model_name='toolinstance',
            index=models.Index(fields=['tenant', 'inspection_status'], name='tool_instan_tenant__96416a_idx'),
        ),
        migrations.AddIndex(
            model_name='toolinstance',
            index=models.Index(fields=['tenant', 'status'], name='tool_instan_tenant__492596_idx'),
        ),
        migrations.AddIndex(
            model_name='toolinstance',
            index=models.Index(fields=['tenant', 'calibration_due_date'], name='tool_instan_tenant__b5a64c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='toolinstance',
            unique_together={('tenant', 'tool', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='toolreservation',
            index=models.Index(fields=['tenant', 'work_order', 'status'], name='tool_reserv_tenant__7af64c_idx'),
        ),
        migrations.AddIndex(
            model_name='toolreservation',
            index=models.Index(fields=['tenant', 'tool', 'status'], name='tool_reserv_tenant__d04c9b_idx'),
        ),
    ]
