# Generated by Django 5.2.17 on 2026-10-03 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_toolinstance_toolreservation_and_more'),
        ('core', '0005_alter_auditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='center_x',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='center_y',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='location',
            name='floor_level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='location',
            name='floorplan_image',
            field=models.TextField(blank=True, default='', help_text='URL hoặc Data URI ảnh sơ đồ mặt bằng'),
        ),
        migrations.AddField(
            model_name='location',
            name='zone_type',
            field=models.CharField(choices=[('STANDARD', 'Tiêu chuẩn'), ('CONTROLLED', 'Kiểm soát đặc thù / Phòng sạch'), ('GENERAL', 'Chung / Toàn nhà máy')], default='STANDARD', max_length=32),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'code'], name='locations_tenant__ac9bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'zone_type'], name='locations_tenant__d0cd3d_idx'),
        ),
    ]
