# Generated by Django 5.2.17 on 2026-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_location_center_x_location_center_y_location_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='zone_type',
            field=models.CharField(choices=[('FLOORPLAN', 'Mặt bằng tổng thể'), ('STANDARD', 'Tiêu chuẩn'), ('CONTROLLED', 'Kiểm soát đặc thù / Phòng sạch'), ('GENERAL', 'Chung / Toàn nhà máy')], default='STANDARD', max_length=32),
        ),
    ]
