# Generated by Django 6.1 on 2026-08-28 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'db_table': 'work_order_attachments',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('input_type', models.CharField(default='PASS_FAIL', max_length=50)),
                ('expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='workorders.workorder')),
            ],
            options={
                'db_table': 'work_order_checklists',
            },
        ),
    ]
