# Generated by Django 6.1 on 2026-08-28 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_meterreading'),
        ('core', '0003_auditlog'),
        ('workorders', '0002_workorderattachment_workorderchecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sparepart')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='workorders.workorder')),
            ],
            options={
                'db_table': 'work_order_materials',
            },
        ),
    ]
