# Generated by Django 5.2.17 on 2026-09-20 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_is_trackable_alter_asset_status_and_more'),
        ('core', '0004_alter_dummytenantmodel_id'),
        ('workorders', '0005_workorder_updated_by_workorderattachment_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='type',
            field=models.CharField(choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('EMERGENCY', 'Emergency'), ('BREAKDOWN', 'Breakdown')], db_index=True, default='CORRECTIVE', max_length=50),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'status', 'type', 'created_at'], name='work_orders_tenant__2e4348_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'completed_at'], name='work_orders_tenant__136eca_idx'),
        ),
    ]
