# Generated by Django 5.2.17 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_action_type'),
        ('workorders', '0006_workorder_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_capitalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='skipped_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='skipped_reference_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressed_pm_orders', to='workorders.workorder'),
        ),
        migrations.CreateModel(
            name='LaborLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('cost_center_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('is_overtime', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_logs', to='workorders.workorder')),
            ],
            options={
                'db_table': 'labor_logs',
                'indexes': [models.Index(fields=['tenant', 'work_order', 'work_date'], name='labor_logs_tenant__a10d56_idx'), models.Index(fields=['tenant', 'technician', 'work_date'], name='labor_logs_tenant__bf41b3_idx')],
            },
        ),
    ]
