# Generated by Django 5.2.17 on 2026-10-02 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_coords_x_asset_coords_y_asset_floor_level_and_more'),
        ('core', '0005_alter_auditlog_action_type'),
        ('workorders', '0007_workorder_actual_cost_workorder_is_capitalized_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='coords_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='coords_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='depends_on_wo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_work_orders', to='workorders.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='floor_level',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_crew_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='min_skill_level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorder',
            name='required_certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='required_skill',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='required_tools',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workorder',
            name='zone_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'status', 'priority'], name='work_orders_tenant__cdbaca_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'depends_on_wo'], name='work_orders_tenant__a59ed9_idx'),
        ),
    ]
