# Generated by Django 5.2.17 on 2026-10-07 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_location_zone_type'),
        ('core', '0005_alter_auditlog_action_type'),
        ('workorders', '0008_workorder_coords_x_workorder_coords_y_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='required_spare_parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GAOptimizationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('current_generation', models.IntegerField(default=0)),
                ('max_generations', models.IntegerField(default=150)),
                ('best_fitness', models.FloatField(default=0.0)),
                ('convergence_history', models.JSONField(blank=True, default=list)),
                ('pareto_solutions', models.JSONField(blank=True, default=list)),
                ('work_order_ids', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ga_jobs', to=settings.AUTH_USER_MODEL)),
                ('floorplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ga_jobs', to='assets.location')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'ga_optimization_jobs',
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='ga_optimiza_tenant__042fc9_idx')],
            },
        ),
    ]
