# Generated by Django 6.1 on 2026-08-28 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_meterreading'),
        ('core', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PmPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('trigger_type', models.CharField(choices=[('TIME', 'Time'), ('USAGE', 'Usage'), ('METER', 'Meter')], max_length=50)),
                ('interval_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('interval_unit', models.CharField(blank=True, choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months'), ('YEARS', 'Years')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_floating_schedule', models.BooleanField(default=False)),
                ('suppress_if_pending', models.BooleanField(default=True)),
                ('lead_time_days', models.IntegerField(default=0)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pm_plans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'pm_plans',
            },
        ),
        migrations.CreateModel(
            name='PmPlanChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('input_type', models.CharField(default='PASS_FAIL', max_length=50)),
                ('expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('pm_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='maintenance.pmplan')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'pm_plan_checklists',
            },
        ),
        migrations.CreateModel(
            name='PmPlanMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pm_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='maintenance.pmplan')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.sparepart')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'pm_plan_materials',
            },
        ),
        migrations.CreateModel(
            name='PmPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('pm_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='maintenance.pmplan')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.tenant')),
            ],
            options={
                'db_table': 'pm_plan_assignments',
                'unique_together': {('tenant', 'pm_plan', 'asset')},
            },
        ),
    ]
